# Intro to PyTorch

## Section 1: Actually activating the virtual environment and opening the Jupyter Notebook

``` source .venv/bin/activate ``` \
``` pip install ipykernel ``` \
``` python -m ipykernel install --user --name=my_venv --display-name "Python (.venv)" ```

Open Jupyter Lab using ``` jupyter lab ``` and when creating a new notebook, ensure that you select the ``` .venv ``` kernel option

## Section 2: Tensors

In [3]:
import torch
scalar = torch.tensor(7) #zero-dimension tensor
print(scalar)
print(scalar.ndim) #will output 0, because it is zero dimensional
print(scalar.item()) #7 items in the tensor

tensor(7)
0
7


A tensor is just a fancy name for a data structure, a data-storing framework. A scalar is basically a zero dimensional tensor, you can check that it's zero dimensional by running ``` print(scalar.ndim) ```, giving the number of dimensions. The scalar does contain items, which you can check using ``` print(scalar.item() ) ```. 

In [10]:
#vector = single-dimensional tensor
import torch
vector = torch.tensor([7 , 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


A vector is a single-dimensional tensor. Again, check this with ``` print(vector.ndim) ```. Running ``` print(vector.item() ) ``` will fail. Since it contains two 7's, running ``` print(vector.shape) ``` will tell you the number of items it has, or, its "shape".

In [13]:
import torch
MATRIX = torch.tensor([[3, 9],
                       [4, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 3,  9],
        [ 4, 10]])
2
torch.Size([2, 2])


This will create a matrix. This will have a two-dimensional shape, as evident by the number of square brackets on one side. Again, run this using ``` print(MATRIX.ndim) ```. Because it is a "square" with a 2*2 shape, running ``` print(MATRIX.shape) ``` will output this.

In [15]:
import torch
MATRIX = torch.tensor([[[1, 2, 3],
                        [6, 10, 12],
                        [2, 5, 10]]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[[ 1,  2,  3],
         [ 6, 10, 12],
         [ 2,  5, 10]]])
3
torch.Size([1, 3, 3])


The torch size will always tell you, in order: The number of matrices, the rows, the columns.

![Local Image](tensor.png)

In [18]:
import torch
x = torch.rand(1, 3, 3)
print(x)
print(x.shape)

tensor([[[0.3158, 0.4150, 0.0334],
         [0.7801, 0.4804, 0.4994],
         [0.1888, 0.9179, 0.0380]]])
torch.Size([1, 3, 3])


Use ``` torch.rand() ``` to create a scalar, vector, or matrix with randomly generated numbers. The numbers you choose in brackets reflect its size.

In [21]:
import torch
x = torch.zeros(size=(1, 3, 3))
print(x)

y = torch.ones(size=(1, 3, 3))
print(y)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [28]:
z = torch.arange(0, 10, 1)
print(z)

x = torch.zeros(size=(1, 3, 3))
print(x)

ten_zeros = torch.zeros_like(input=z)
print(ten_zeros)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


Use ``` torch.arange() ``` to create a scalar, vector, or matrix that starts, ends, and counts in the steps that you choose. In this case, the code tells the program to start from 0, end at 10, and move every 1 step.

You can also use ``` torch.zeros_like(input) ``` or ``` torch.ones_like(input) ``` to create tensors of same shape as the input but instead fill the gaps with zeros or ones.

In [29]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6460, 0.6807, 0.5820, 0.5707],
        [0.8145, 0.8236, 0.2771, 0.5731],
        [0.9811, 0.0556, 0.2643, 0.4308]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Use this code snippet to get information about a tensor quickly.

### Simple math using tensors

In [32]:
add = torch.rand(1, 3, 3)
print(add)

print(add + 10)

tensor([[[0.7693, 0.6897, 0.4628],
         [0.7985, 0.9285, 0.9167],
         [0.9039, 0.0470, 0.8206]]])
tensor([[[10.7693, 10.6897, 10.4628],
         [10.7985, 10.9285, 10.9167],
         [10.9039, 10.0470, 10.8206]]])


This will add the number 10 to each number in the matrix

In [34]:
subtract = torch.rand(1, 3, 3)
print(subtract)
print(subtract - 10)
print(subtract)

tensor([[[0.7041, 0.7511, 0.2668],
         [0.6262, 0.3957, 0.5647],
         [0.9598, 0.9240, 0.5287]]])
tensor([[[-9.2959, -9.2489, -9.7332],
         [-9.3738, -9.6043, -9.4353],
         [-9.0402, -9.0760, -9.4713]]])
tensor([[[0.7041, 0.7511, 0.2668],
         [0.6262, 0.3957, 0.5647],
         [0.9598, 0.9240, 0.5287]]])


But this won't change the actual tensor, i.e. ``` print(subtract) ``` will give the same tensor that you generated.

In [40]:
addpy = torch.tensor([1, 3, 3])
print(addpy)
torch.multiply(addpy, 10)

tensor([1, 3, 3])


tensor([10, 30, 30])